# Generated by Django 3.2.4 on 2021-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nomCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
                ('descCategoria', models.CharField(max_length=200, verbose_name='Descripcion de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('idSoftware', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del Software')),
                ('nomSoftware', models.CharField(max_length=50, verbose_name='Nombre del Software')),
                ('descSoftware', models.CharField(max_length=300, verbose_name='Descripcion del Software')),
            ],
        ),
    ]
