# Generated by Django 3.2.4 on 2021-06-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_software_catsoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitosMin',
            fields=[
                ('idRequisito', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de los Requisitos')),
                ('sistema', models.CharField(max_length=50, verbose_name='Sistema operativo minimo')),
                ('procesador', models.CharField(max_length=10, verbose_name='Procesador mínimo')),
                ('memoria', models.IntegerField(verbose_name='Ram minima')),
                ('grafico', models.CharField(max_length=80, verbose_name='GPU Minima')),
                ('almacenamiento', models.IntegerField(verbose_name='Almacenamiento minimo')),
                ('idSoftware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.software')),
            ],
        ),
    ]
